---
 - hosts: all
   vars:
     ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

   tasks:

    - name: Adding user
      user:
        name: bro
        groups: sudo
        shell: /bin/bash

    - name: Add ssh keys to remote host
      authorized_key:
        user: goto
        state: present
        key: "{{ lookup('file', '/home/goto/.ssh/id_rsa.pub') }}"

    - name: push config /etc/sudoers
      template:
        src=templates/sudoers.j2
        dest=/etc/sudoers
        owner=root
        group=root
        mode=0600
